# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mitchell Atlas
tagline:             'Nuclear engineering for fun and profit'
description:         'Main menu'
url:                 http://xatlasm.github.io
baseurl:             /
paginate:            5
github:                     
  repo:              https://github.com/xatlasm/xatlasm.github.io
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Mitchell Atlas
  url:               https://twitter.com/xatlasm
  email:             xatlasm@gmail.com

# Custom vars
version:             1.0.0

# Tracking
google_analytics: UA-46827087-1

# Comments
disqus: xatlasm

